algoritmo "Verifica se número é divisível por 3 e por 7"
var
n1:inteiro
inicio
escreval("Informe um número para verificar se ele é divisível por 3 e por 7")
leia(n1)
se ((n1 mod 3)=0) entao
   se((n1 mod 7)=0) entao
   escreva("O número é divisível por 3 e por 7")
   senao
   escreva("O número não é divisível por 3 e por 7")
   fimse
senao
escreva("O número não é divisível por 3 e por 7")
fimse




fimalgoritmo